"""Governed hybrid retrieval over deterministic and derived indexes."""

from .hybrid import HybridRetriever
from .models import (
    EvidenceClaim,
    EvidenceConflict,
    HybridEvidence,
    HybridRetrievalResponse,
    IndexedKnowledgeDocument,
    RerankedEvidence,
    RetrievalScope,
    VectorHit,
)
from .index_governance import (
    IdentifiedEmbeddingProvider,
    IndexActivationRecord,
    IndexBuildReport,
    IndexCanaryReport,
    IndexIdentity,
    QdrantIndexGovernance,
)
from .model_runtime import (
    EmbeddingRequest,
    EmbeddingResponse,
    ModelErrorResponse,
    ModelHealthRequest,
    ModelHealthResponse,
    ModelProvenance,
    ModelServiceError,
    ModelTransport,
    ModelTransportError,
    RemoteJsonlExchange,
    RemoteJsonlModelTransport,
    RerankDocument,
    RerankRequest,
    RerankResponse,
    RerankScore,
    SubprocessJsonlModelTransport,
)
from .provenance import ProvenanceError, ProvenanceValidator
from .qwen3 import (
    QWEN3_EMBEDDING_DIMENSION,
    QWEN3_EMBEDDING_MODEL_ID,
    QWEN3_EMBEDDING_REVISION,
    QWEN3_RERANKER_MODEL_ID,
    QWEN3_RERANKER_REVISION,
    Qwen3EmbeddingProvider,
    Qwen3RerankerProvider,
    RerankingProvider,
)
from .source import FilesystemKnowledgeSource
from .vector_index import EmbeddingProvider, LocalQdrantIndex

__all__ = [
    "EvidenceClaim",
    "EvidenceConflict",
    "EmbeddingProvider",
    "EmbeddingRequest",
    "EmbeddingResponse",
    "FilesystemKnowledgeSource",
    "HybridEvidence",
    "HybridRetrievalResponse",
    "HybridRetriever",
    "IdentifiedEmbeddingProvider",
    "IndexActivationRecord",
    "IndexBuildReport",
    "IndexCanaryReport",
    "IndexIdentity",
    "IndexedKnowledgeDocument",
    "LocalQdrantIndex",
    "ModelErrorResponse",
    "ModelHealthRequest",
    "ModelHealthResponse",
    "ModelProvenance",
    "ModelServiceError",
    "ModelTransport",
    "ModelTransportError",
    "ProvenanceError",
    "ProvenanceValidator",
    "QWEN3_EMBEDDING_DIMENSION",
    "QWEN3_EMBEDDING_MODEL_ID",
    "QWEN3_EMBEDDING_REVISION",
    "QWEN3_RERANKER_MODEL_ID",
    "QWEN3_RERANKER_REVISION",
    "QdrantIndexGovernance",
    "Qwen3EmbeddingProvider",
    "Qwen3RerankerProvider",
    "RemoteJsonlExchange",
    "RemoteJsonlModelTransport",
    "RerankDocument",
    "RerankedEvidence",
    "RerankingProvider",
    "RerankRequest",
    "RerankResponse",
    "RerankScore",
    "RetrievalScope",
    "SubprocessJsonlModelTransport",
    "VectorHit",
]
