"""Closed vocabularies used by versioned contracts and graph transitions."""

from __future__ import annotations

from enum import StrEnum


class AuditStatus(StrEnum):
    PASS = "PASS"
    WARN = "WARN"
    REJECT = "REJECT"
    NEEDS_UNIT_CONFIRMATION = "NEEDS_UNIT_CONFIRMATION"
    NEEDS_EVIDENCE = "NEEDS_EVIDENCE"


class ResultStatus(StrEnum):
    VALID = "RESULT_VALID"
    INVALID = "RESULT_INVALID"
    NOT_EVALUATED = "NOT_EVALUATED"


class WorkflowIntent(StrEnum):
    READ_ONLY = "READ_ONLY"
    SMOKE = "SMOKE"
    FULL_RUN = "FULL_RUN"


class WorkflowStage(StrEnum):
    RECEIVED = "RECEIVED"
    PHYSICAL_AUDIT = "PHYSICAL_AUDIT"
    NEEDS_UNIT_CONFIRMATION = "NEEDS_UNIT_CONFIRMATION"
    NEEDS_UNIT_WARNING_APPROVAL = "NEEDS_UNIT_WARNING_APPROVAL"
    NEEDS_METRIC_PRIORITY = "NEEDS_METRIC_PRIORITY"
    NEEDS_DIAGNOSTIC_EVIDENCE = "NEEDS_DIAGNOSTIC_EVIDENCE"
    READY_FOR_DECISION = "READY_FOR_DECISION"
    NEEDS_EXPERIMENT_APPROVAL = "NEEDS_EXPERIMENT_APPROVAL"
    SMOKE_APPROVED = "SMOKE_APPROVED"
    SMOKE_RUNNING = "SMOKE_RUNNING"
    SMOKE_VALIDATING = "SMOKE_VALIDATING"
    NEEDS_SMOKE_VALIDATION = "NEEDS_SMOKE_VALIDATION"
    NEEDS_FULL_RUN_APPROVAL = "NEEDS_FULL_RUN_APPROVAL"
    FULL_APPROVED = "FULL_APPROVED"
    FULL_RUNNING = "FULL_RUNNING"
    RESULT_INVALID = "RESULT_INVALID"
    REJECTED = "REJECTED"
    COMPLETED = "COMPLETED"


class MetricRole(StrEnum):
    HARD_CONSTRAINT = "HARD_CONSTRAINT"
    PRIMARY = "PRIMARY"
    SECONDARY = "SECONDARY"
    GUARDRAIL = "GUARDRAIL"
    DIAGNOSTIC = "DIAGNOSTIC"


class MetricDirection(StrEnum):
    MINIMIZE = "MINIMIZE"
    MAXIMIZE = "MAXIMIZE"


class MetricEvidenceBasis(StrEnum):
    PHYSICAL_MODEL = "PHYSICAL_MODEL"
    REFERENCE_EVIDENCE = "REFERENCE_EVIDENCE"
    BASELINE_RUN = "BASELINE_RUN"


class AggregationPolicy(StrEnum):
    LEXICOGRAPHIC = "LEXICOGRAPHIC"
    PARETO = "PARETO"
    SCALAR = "SCALAR"


class ParameterConsumption(StrEnum):
    DERIVED_MANIFEST = "DERIVED_MANIFEST"
    RAW_CODE_PATH = "RAW_CODE_PATH"


class ReferenceKind(StrEnum):
    ANALYTIC = "ANALYTIC"
    EXPERIMENTAL = "EXPERIMENTAL"
    NUMERICAL = "NUMERICAL"
    TEACHER_MODEL = "TEACHER_MODEL"
    OBSERVATIONAL = "OBSERVATIONAL"


class ApprovalKind(StrEnum):
    UNIT_WARNING = "UNIT_WARNING"
    METRIC_PRIORITY = "METRIC_PRIORITY"
    EXPERIMENT = "EXPERIMENT"
    FULL_RUN = "FULL_RUN"
    FILE_MODIFICATION = "FILE_MODIFICATION"
    RUN_CANCELLATION = "RUN_CANCELLATION"
    KNOWLEDGE_PROMOTION = "KNOWLEDGE_PROMOTION"
    SKILL_PROMOTION = "SKILL_PROMOTION"


class ApprovalDecision(StrEnum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class DecisionStatus(StrEnum):
    ACCEPT = "ACCEPT"
    REJECT = "REJECT"
    NEEDS_EVIDENCE = "NEEDS_EVIDENCE"


class RunEventType(StrEnum):
    RUN_QUEUED = "RUN_QUEUED"
    RUN_STARTED = "RUN_STARTED"
    METRIC_UPDATED = "METRIC_UPDATED"
    RESOURCE_UPDATED = "RESOURCE_UPDATED"
    CHECKPOINT_WRITTEN = "CHECKPOINT_WRITTEN"
    LOSS_SPIKE = "LOSS_SPIKE"
    NAN_DETECTED = "NAN_DETECTED"
    GPU_OOM = "GPU_OOM"
    LOG_STALLED = "LOG_STALLED"
    ARTIFACT_MISSING = "ARTIFACT_MISSING"
    EARLY_STOP_TRIGGERED = "EARLY_STOP_TRIGGERED"
    RUN_FINISHED = "RUN_FINISHED"
    RUN_FAILED = "RUN_FAILED"


class RunSubmissionStatus(StrEnum):
    MANIFEST_RECORDED = "MANIFEST_RECORDED"
    PREPARED = "PREPARED"
    RUNNING = "RUNNING"
    RUNNING_UNKNOWN = "RUNNING_UNKNOWN"
    CANCELLING = "CANCELLING"
    CANCELLED = "CANCELLED"
    COLLECTING = "COLLECTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class BackendRunPhase(StrEnum):
    PREPARED = "PREPARED"
    RUNNING = "RUNNING"
    RUNNING_UNKNOWN = "RUNNING_UNKNOWN"
    CANCELLING = "CANCELLING"
    CANCELLED = "CANCELLED"
    COLLECTING = "COLLECTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class ArtifactCollectionStatus(StrEnum):
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"


class MonitorOutcome(StrEnum):
    HEALTHY = "HEALTHY"
    MILESTONE = "MILESTONE"
    ANOMALY = "ANOMALY"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class KnowledgeKind(StrEnum):
    WIKI = "WIKI"
    SKILL = "SKILL"


class EvidenceLevel(StrEnum):
    SMOKE = "SMOKE"
    SCIENTIFIC = "SCIENTIFIC"


class ClaimScope(StrEnum):
    WORKFLOW_ONLY = "WORKFLOW_ONLY"
    SCIENTIFIC_EFFECTIVENESS = "SCIENTIFIC_EFFECTIVENESS"


class KnowledgeValidity(StrEnum):
    CANDIDATE = "CANDIDATE"
    VALID = "VALID"
    SUPERSEDED = "SUPERSEDED"
    INVALIDATED = "INVALIDATED"
